"""
Database connection and schema setup.

Responsibilities:
  - Connect to PostgreSQL using environment variables
  - Create all tables and indexes (idempotent — safe to run multiple times)

Tables:
  gup_rows              Raw Excel data — source of truth, never modified
  repair_documents      One row per unique repair document (108 rows)
  repair_document_cars  Which cars each document applies to
  car_embeddings        One row per unique car configuration (157 rows)

Note: Embedding columns (vector(768)) are created here but left NULL.
      Embeddings are generated by the backend, not this seeder.
"""

import os
import psycopg2


def get_connection():
    """
    Returns a psycopg2 connection using environment variables.
    Raises EnvironmentError if any required variable is missing.
    """
    required = ["DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASSWORD"]
    missing = [v for v in required if not os.getenv(v)]
    if missing:
        raise EnvironmentError(f"Missing environment variables: {missing}")

    return psycopg2.connect(
        host=os.getenv("DB_HOST"),
        port=int(os.getenv("DB_PORT")),
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
    )


def create_schema(conn):
    """
    Creates all tables and indexes.
    Uses IF NOT EXISTS — completely safe to run multiple times.
    """
    with conn.cursor() as cur:

        # pgvector extension — required for vector(768) columns
        cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")

        # ── gup_rows ──────────────────────────────────────────────────────────
        # Mirrors the Excel file exactly. One row per Excel row.
        # This is the raw source data — never modified after initial load.
        cur.execute("""
            CREATE TABLE IF NOT EXISTS gup_rows (
                id                       SERIAL PRIMARY KEY,
                id_macchina              TEXT NOT NULL,
                marca_macchina           TEXT NOT NULL,
                modello_macchina         TEXT NOT NULL,
                anno_inizio_macchina     INTEGER,
                anno_fine_macchina       INTEGER,
                alimentazione_macchina   TEXT,
                motorizzazione_macchina  TEXT,
                kw_macchina              INTEGER,
                cavalli_macchina         INTEGER,
                codice_motore_macchina   TEXT NOT NULL,
                id_documento             TEXT NOT NULL,
                sigla_documento          TEXT,
                titolo_documento         TEXT,
                parole_chiave            TEXT,
                capitolo_documento       TEXT,
                contenuto_documento      TEXT,
                created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_gup_rows_sigla
                ON gup_rows (sigla_documento);
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_gup_rows_car
                ON gup_rows (marca_macchina, modello_macchina, codice_motore_macchina);
        """)

        # ── repair_documents ──────────────────────────────────────────────────
        # One row per unique repair document.
        # Populated from gup_rows by grouping the three chapters.
        # embedding is NULL until the backend generates it.
        cur.execute("""
            CREATE TABLE IF NOT EXISTS repair_documents (
                id                   SERIAL PRIMARY KEY,
                sigla_documento      TEXT NOT NULL UNIQUE,
                titolo_documento     TEXT,
                parole_chiave        TEXT,
                grado_attendibilita  SMALLINT NOT NULL DEFAULT 1,
                identificazione      TEXT,
                procedura            TEXT,
                embed_text           TEXT,
                embedding            vector(768),
                search_vector        tsvector,
                created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_repair_docs_search_vector
                ON repair_documents USING gin (search_vector);
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_repair_docs_embedding
                ON repair_documents USING hnsw (embedding vector_cosine_ops)
                WHERE embedding IS NOT NULL;
        """)

        # ── repair_document_cars ──────────────────────────────────────────────
        # Join table: which car configurations each document applies to.
        cur.execute("""
            CREATE TABLE IF NOT EXISTS repair_document_cars (
                id                      SERIAL PRIMARY KEY,
                repair_document_id      INTEGER NOT NULL
                    REFERENCES repair_documents(id) ON DELETE CASCADE,
                id_macchina             TEXT NOT NULL,
                marca_macchina          TEXT NOT NULL,
                modello_macchina        TEXT NOT NULL,
                motorizzazione_macchina TEXT,
                codice_motore_macchina  TEXT NOT NULL,
                alimentazione_macchina  TEXT,
                anno_inizio_macchina    INTEGER,
                anno_fine_macchina      INTEGER,
                kw_macchina             INTEGER,
                cavalli_macchina        INTEGER,
                UNIQUE (repair_document_id, id_macchina)
            );
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_repair_doc_cars_codice_motore
                ON repair_document_cars (codice_motore_macchina);
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_repair_doc_cars_marca_modello
                ON repair_document_cars (marca_macchina, modello_macchina);
        """)

        # ── car_embeddings ────────────────────────────────────────────────────
        # One row per unique car configuration.
        # embedding is NULL until the backend generates it.
        cur.execute("""
            CREATE TABLE IF NOT EXISTS car_embeddings (
                id                      SERIAL PRIMARY KEY,
                id_macchina             TEXT NOT NULL UNIQUE,
                marca_macchina          TEXT NOT NULL,
                modello_macchina        TEXT NOT NULL,
                motorizzazione_macchina TEXT,
                codice_motore_macchina  TEXT NOT NULL,
                alimentazione_macchina  TEXT,
                anno_inizio             INTEGER,
                anno_fine               INTEGER,
                kw                      INTEGER,
                cavalli                 INTEGER,
                embed_text              TEXT,
                embedding               vector(768),
                created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_car_embeddings_codice_motore
                ON car_embeddings (codice_motore_macchina);
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_car_embeddings_embedding
                ON car_embeddings USING hnsw (embedding vector_cosine_ops)
                WHERE embedding IS NOT NULL;
        """)

    conn.commit()
    print("Schema ready.")
