"""
SemaRepair Data Seeder — entry point.

Does exactly one thing: loads the Excel data into PostgreSQL.
No embeddings. No external API calls. No business logic.

Execution order:
  1. Connect to database
  2. Create schema (tables + indexes)
  3. Parse Excel file
  4. Load gup_rows          (2000 rows — raw source data)
  5. Load repair_documents  (108 rows — one per unique document)
  6. Load repair_document_cars (666 rows — document to car mapping)
  7. Load car_embeddings    (157 rows — unique car configs, no embeddings yet)

Idempotent — safe to run multiple times.
Estimated run time: under 15 seconds.
"""

import sys
from db import get_connection, create_schema
from parser import parse_excel
from seeder import (
    seed_gup_rows,
    seed_repair_documents,
    seed_repair_document_cars,
    seed_car_embeddings,
)

EXCEL_PATH = "/app/GUP_PER_IA.xlsx"


def main():
    print("=" * 50)
    print("SemaRepair Data Seeder")
    print("=" * 50)

    # Step 1 — Connect
    print("\n[1] Connecting to database...")
    try:
        conn = get_connection()
        print("  Connected.")
    except Exception as e:
        print(f"  ERROR: {e}")
        sys.exit(1)

    # Step 2 — Schema
    print("\n[2] Creating schema...")
    try:
        create_schema(conn)
    except Exception as e:
        print(f"  ERROR: {e}")
        conn.close()
        sys.exit(1)

    # Step 3 — Parse Excel
    print("\n[3] Parsing Excel file...")
    try:
        rows = parse_excel(EXCEL_PATH)
    except FileNotFoundError:
        print(f"  ERROR: File not found at {EXCEL_PATH}")
        conn.close()
        sys.exit(1)

    # Step 4 — gup_rows
    print("\n[4] Loading gup_rows...")
    seed_gup_rows(conn, rows)

    # Step 5 — repair_documents
    print("\n[5] Loading repair_documents...")
    seed_repair_documents(conn)

    # Step 6 — repair_document_cars
    print("\n[6] Loading repair_document_cars...")
    seed_repair_document_cars(conn)

    # Step 7 — car_embeddings
    print("\n[7] Loading car_embeddings...")
    seed_car_embeddings(conn)

    conn.close()

    print("\n" + "=" * 50)
    print("Done. Database is ready.")
    print("Embeddings will be generated by the backend on startup.")
    print("=" * 50)


if __name__ == "__main__":
    main()
